services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: lmunoz-q
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./customer:/docker-entrypoint-initdb.d/customer
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

